### ISSUE TITLE
Inconsistent ledger_hash in catching up.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [CounterpartyXCP/counterparty-core#1094]
In a particular case, the counterparty-server is aborted by "Inconsistent ledger_hash".

I got this on Monaparty mainnet. I suppose It can be reproduced on Counterparty.
I have already created the patch. I'll send PR later.

**Comment by chiguireitor** [comment]
Sometimes this can be caused by changes that change consensus. In other cases, the addition of new columns that don't affect consensus, but affect the queries, happens.

You can rollback to the previous block so you clear the existent parsed data on db. Sometimes these rollbacks can cause a full reparse (this is why we haven't yet released the latest version of counterparty, we had to do 2 full reparses because some changes we made).

**Comment by cryptcoin-junkey** [comment]
Reproduction step is:

```
fednode start counterparty
fednode stop counterparty
sleep 3600
fednode start counterparty
(wait until follow up is done.)
fednode reparse
```

The root cause is simple. There is a lack of referring hashes stored in the previous block at `follow()`.
I'm blushing up my patch. I'll send PR within a day.

**Comment by cryptcoin-junkey** [comment]
I sent my PR.
And it looks some more patches are required. I encountered the another pattern of inconsistent hashes. I'm inspecting now.

**Comment by cryptcoin-junkey** [comment]
I feel I close to the bingo.
It seems `util.BLOCK_LEDGER` is not ordered by `tx_index` in some cases.

**Comment by chiguireitor** [comment]
hmmmm.... that could be possible, i've found that nailing the ledger_hash from other software besides the python version of counterparty is kinda hard.... do you have a specific scenario where this is happening?

**Comment by cryptcoin-junkey** [comment]
In my case, re-parsing the block includes a MPMA message on Monaparty mainnet.
I think this will be fixed by sorting `util.BLOCK_LEDGER`. But it is just a workaround, not the best.
I'm tracing the code deeper now.

**Comment by adamkrellenstein** [comment]
See #1309
