### ISSUE TITLE
Test Idempotent API Endpoints against Node in CI, using Example Calls in Documentation

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1739]
Check performance when we do—make sure latency is below a certain threshold.

@ouziel-slama this seem reasonable?

**Comment by ouziel-slama** [comment]
yeah definitely that’s what we should do! just connect our Blueprint to a Dredd.. but it's not simple :) because most of our endpoints are not idempotent and often require a context which expires.. For example to compose a BTCPay you need a valid order match.. ( To generate the doc, I cheated and commented out checks in the code).
A priori to be able to systematically test all endpoints we would need a regtest node where we reload fixtures before each test..

**Comment by adamkrellenstein** [comment]
hm yeah. okay maybe in version 1 of this, we just check the idempotent ones?

**Comment by ouziel-slama** [comment]
yeah sounds good!

**Comment by adamkrellenstein** [comment]
See https://github.com/CounterpartyXCP/counterparty-core/issues/1654

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/1751
Only `compose`, `bitcoin`, `mempool` and `/` routes are not tested with `dredd` .
See `dredd.yml` automatically generated with the blueprint doc.
