### ISSUE TITLE
[WIP] API v2 Tweaks

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1786]
* [x] Transactions by tx index
* [x] Issuances/burns/dispenser creations/etc. for each block
* [x] Sends etc. by hash
* [x] Last `N` sends, issuances, etc.
* [x] Enable pagination for all routes (e.g. `/blocks/<block>/transactions?limit=10&offset=0`)
* [x] Fancier pagination (e.g. cursor-based pagination; see https://slack.engineering/evolving-api-pagination-at-slack/)
* [x] Offset doesn't work with `/blocks`
* [x] Offset doesn't work with `/events/SEND`
* [x] Docs should specify everywhere whether quantity is sats or BTC / XCP / etc.
* [x] Asset names are case-sensitive
* [x] Support pagination and limit for `addresses/$address/balances?limit=10`
* [x] Issuances by address (this looks like just an oversight)
* [x] Fetch block by hash
* [x] `verbose=true` doesn't do anything for `/assets/$asset/holders`

(It'd be great to update the `dev` server with these routes as they become available.)

**Comment by adamkrellenstein** [comment]
This is weird:

<img width="541" alt="Screenshot 2024-05-11 at 9 51 08 PM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/d1a4a10d-ae6f-47ad-9465-7498c488f399">

**Comment by loon3** [comment]
```/assets/<asset>/orders``` is missing limit and offset

**Comment by ouziel-slama** [comment]
> * [ ]  Issuances/burns/dispenser creations/etc. for each block

There are already a lot of `/v2/blocks/<int:block_index>/*` routes, for example `/v2/blocks/<int:block_index>/issuances`. Some are missing because it was not clear what it should return. However, to know everything that is happening in a block it is recommended to use the following route: `/v2/blocks/<int:block_index>/events/<event>`.
For example for dispensers it is very simple and precise to use:

`/v2/blocks/<int:block_index>/events/OPEN_DISPENSER`
`/v2/blocks/<int:block_index>/events/DISPENSER_UPDATE`
`/v2/blocks/<int:block_index>/events/REFILL_DISPENSER`
`/v2/blocks/<int:block_index>/events/DISPENSE`

than a possible route `/v2/blocks/<int:block_index>/dispensers`.

I will add the following list of events to the API documentation:

### Blocks and Transactions
`NEW_BLOCK`
`NEW_TRANSACTION`
`NEW_TRANSACTION_OUTPUT`
`BLOCK_PARSED`
`TRANSACTION_PARSED`

### Asset Movements
`DEBIT`
`CREDIT`
`ENHANCED_SEND`
`MPMA_SEND`
`SEND`
`ASSET_TRANSFER`
`SWEEP`
`ASSET_DIVIDEND`

### Asset Creation and Destruction
`RESET_ISSUANCE`
`ASSET_CREATION`
`ASSET_ISSUANCE`
`ASSET_DESTRUCTION`

### DEX
`OPEN_ORDER`
`ORDER_MATCH`
`ORDER_UPDATE`
`ORDER_FILLED`
`ORDER_MATCH_UPDATE`
`BTC_PAY`
`CANCEL_ORDER`
`ORDER_EXPIRATION`
`ORDER_MATCH_EXPIRATION`

### Dispenser
`OPEN_DISPENSER`
`DISPENSER_UPDATE`
`REFILL_DISPENSER`
`DISPENSE`

### Broadcast
`BROADCAST`

### Bets
`OPEN_BET`
`BET_UPDATE`
`BET_MATCH`
`BET_MATCH_UPDATE`
`BET_EXPIRATION`
`BET_MATCH_EXPIRATION`
`BET_MATCH_RESOLUTON`
`CANCEL_BET`

### Burns
`BURN`

### RPS
`OPEN_RPS`
`RPS_MATCH`
`RPS_EXPIRATION`
`RPS_MATCH_EXPIRATION`
`RPS_RESOLVE`
`RPS_MATCH_UPDATE`
`RPS_UPDATE`
`CANCEL_RPS`

**Comment by adamkrellenstein** [comment]
okay great! that makes sense. and it'll be nice to have all of those data types documented as well :)

**Comment by ouziel-slama** [comment]
@niftyboss1 just added the following routes:

```
"/v2/assets/<asset>/dispenses": ledger.get_dispenses_by_asset
"/v2/addresses/<address>/dispenses/sends": ledger.get_dispenses_by_source,
"/v2/addresses/<address>/dispenses/receives": ledger.get_dispenses_by_destination,
"/v2/addresses/<address>/dispenses/sends/<asset>": ledger.get_dispenses_by_source_and_asset,
"/v2/addresses/<address>/dispenses/receives/<asset>": ledger.get_dispenses_by_destination_and_asset,
```

**Comment by ouziel-slama** [comment]
> Sends etc. by hash

@adamkrellenstein I think this new routes answer the need, please confirm:
```
"/v2/transactions/<int:tx_index>/events": ledger.get_events_by_transaction_index,
"/v2/transactions/<tx_hash>/events": ledger.get_events_by_transaction_hash,
"/v2/transactions/<int:tx_index>/events/<event>": ledger.get_events_by_transaction_index_and_event,
"/v2/transactions/<tx_hash>/events/<event>": ledger.get_events_by_transaction_hash_and_event,
```
same reasoning as for blocks.. the easiest thing is to use events to get exactly what you want!

> Last N sends, issuances, etc.

idem for this. I think you can get what you want with this, please confirm :
```
"/v2/events/<event>": ledger.get_events_by_name,
```
(this route accepts the params `last` and `limit`. `last` being a cursor on the `event_index` field)

**Comment by adamkrellenstein** [comment]
hm, I think that'll work. It feels a bit weird to me that *sometimes* I should use `SEND` events and sometimes e.g. `/sends`, when really I want the same thing both times... but let's see how my usage pattern evolves.

**Comment by ouziel-slama** [comment]
> hm, I think that'll work. It feels a bit weird to me that _sometimes_ I should use `SEND` events and sometimes e.g. `/sends`, when really I want the same thing both times... but let's see how my usage pattern evolves.

I agree.. I didn't want to be too controversial but generally speaking the idea behind the API:
- if you are developing an explorer and you need information by blocks and by transactions then only use events.
- if you are developing a wallet and you need information by address and assets then use the other routes.
