### ISSUE TITLE
Be Able to Lock Descriptions

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1857]
As far as I'm concerned this was a simple oversight on my part when I developed the feature 10 years ago.

The main objection to implementing this feature seems to be that there exist hacky workarounds, and there's a general resistance to any protocol change that could in any way affect the value of historical assets that implemented those hacky workarounds. [There is a lot of confusion around what the word "immutability" means.](https://github.com/CounterpartyXCP/Forum/discussions/135#discussioncomment-9498641) :/ The simple fact is that this feature is in high demand... because it's useful; and it's extremely simple to implement.

Previous discussion has been held here: https://github.com/CounterpartyXCP/Forum/discussions/135

Is it possible to lock the description independently?

**Comment by mikeinspace** [comment]
Bitcoin Stamps has always treated the description as "locked" by ignoring updates. This is part of the "immutability" meme.

So no objections to this change on my end. Not sure why this change would impact the value of "historic NFTs" tbh. In my view, historic NFTs should not be touched at this point. It would be like putting new arms on the Venus de Milo statue or setting the Tower of Pisa straight.

**Comment by keyuno** [comment]
I understand that you are one of the founders of Counterparty, and it might be difficult for you to accept that Counterparty is not used for its original purpose. Things have evolved towards collectibles, and there's no turning back.

However, it seems that you neither understand nor care to learn about collectibles, digital or otherwise. Please do some research and understand that any change to a collectible can significantly affect its perceived value, which is what we're dealing with—perception. There are numerous examples, like collectible cards, coins, etc., where these details matter.

> The main objection to implementing this feature seems to be that there exist hacky workarounds, and there's a general resistance to any protocol change that could in any way affect the value of historical assets that implemented those hacky workarounds.

Hackiness and elegance are subjective, and in this case, the issue isn't about those who burned ownership. It's about assets considered 'locked' that, if this change is implemented, will be vulnerable to attacks on their perceived status of being truly locked.

If this change is implemented, locked assets that derive their value from being unique 1/1 NFTs like OLGA will face a dilemma. Should they lock the description and risk altering the asset, potentially causing the market to perceive it as completed in 2024 instead of 2014, thereby losing its historic value? Or should they not lock the asset and risk narrative attacks from those who did?

In the absence of genuine technical necessity, 'elegance' is not a sufficient reason to disrupt the asset structure, especially when dealing with a market centered around the [store of value](https://vimeo.com/833543207) use case.

**Comment by pinnate-modo** [comment]
Another one of the founders here, and my support for this change is not because Counterparty is used in a way I didn't originally envision. 

The arguments I've seen against making descriptions optionally lockable are:
1. description locking will affect the economic value of the assets.
2. description locking can already be done by sending an asset's issuance rights to an unspendable address.

(1) and (2) directly contradict each other. If you can already accomplish description locking through a bizarre workaround then what is the perceived risk to making it an explicit feature?

Furthermore, why does description locking imperil the economic value of Counterparty assets, but the ability to transfer issuance rights (*one* consequence of which may be locking an asset's description) does not?

In any case, I agree that not having lockable descriptions was an oversight in the original design of issuances, but IMO it should be independent of quantity locking.

**Comment by adamkrellenstein** [comment]
Also the creator of OLGA is himself in favor of the proposal: https://github.com/CounterpartyXCP/Forum/discussions/135#discussioncomment-9496367

**Comment by keyuno** [comment]
> description locking will affect the economic value of the assets.

It **might** affect the value of the assets from a collector's perspective, as I previously explained, mentioning the  [dilemma](https://github.com/CounterpartyXCP/counterparty-core/issues/1857#issuecomment-2146290770) that asset owners will face. 

> Furthermore, why does description locking imperil the economic value of Counterparty assets, but the ability to transfer issuance rights (one consequence of which may be locking an asset's description) does not?

Disrupting the established asset structure without a good reason is a slippery slope; if we change something without real technical necessity, what other superfluous 'modifications' might we bring in down the line that could potentially undermine the value of assets? This introduces market uncertainty that can be easily avoided.

**Comment by keyuno** [comment]
> Also the creator of OLGA is himself in favor of the proposal: [CounterpartyXCP/Forum#135 (comment)](https://github.com/CounterpartyXCP/Forum/discussions/135#discussioncomment-9496367)

As with collectibles, the details matter. The creator of OLGA supports introducing this change provided collectors overwhelmingly favor it after hearing the arguments. However, I do not see **overwhelming** support for it.

**Comment by pinnate-modo** [comment]
>Disrupting the established asset structure without a good reason is a slippery slope; if we change something without real technical necessity, what other superfluous 'modifications' might we bring in down the line that could potentially undermine the value of assets? This introduces market uncertainty that can be easily avoided.

Again, you can already functionally do the same thing by throwing away the issuance rights. So what new uncertainty are you worried about?

**Comment by DerpHerpenstein** [comment]
I think this is good. If an asset creator wants to lock their description, that should be an option and it shouldn't require burning asset ownership

**Comment by jotapea** [comment]
The current issuance design already allows "description immutability" **guarantees** for asset issuers that want it. In its most optimal use case, it would be a subasset transfer to a burn issuer.

I can understand this is imperfect, but wanted to bring it up because this one has no drawback of losing subasset issuing capability (it never had it).

On the contrary, there is no guarantee this "upgrade" is later reverted in a future Counterparty version.

So, I still lean more into @keyuno 's "[If it ain't broke, don't fix it.](https://github.com/CounterpartyXCP/Forum/discussions/135#discussioncomment-8431385)" side.

**Comment by reinamora137** [comment]
I would expect that the ability to lock descriptions would ADD value to historical assets. 

If an issuer locks the description then any collector will rest assured that the issuer/creator/owner will not change the description. Especially in the case where issuance ownership is transferred.  I understand this may be a problem if the asset is linking to a temporary web3 resource/URI, in such a case the asset owner may want it perpetually mutable.

If description cannot be locked, then you could use the same rationale to disable the locking of asset supply. 

Everything should be easily mutable or immutable at the creators wish imo. Seems like a simple optional additional to give users flexibility.

**Comment by keyuno** [comment]
> If an issuer locks the description then any collector will rest assured that the issuer/creator/owner will not change the description.

Updating the description doesn't erase the past, everything is recorded and lives forever on bitcoin. 

> Everything should be easily mutable or immutable at the creators wish imo. 

Insisting on promoting the 'immutable' versus 'mutable' angle only strengthens the main argument: this unnecessary locking "feature" will be used in narrative attacks.

**Comment by davestaxcp** [comment]
> Updating the description doesn't erase the past, everything is recorded and lives forever on bitcoin.

- but it adds a feature that most of the community has been in favor of for many years as long as it is optional on any asset

> Everything should be easily mutable or immutable at the creators wish imo

- which is the reason the original creator might wish to lock description to their liking and sell or use the token ownership in a different way

> Insisting on promoting the 'immutable' versus 'mutable' angle only strengthens the main argument: this unnecessary locking "feature" will be used in narrative attacks.

- narrative attacks on anything are to be expected
- the good narrative here is more value and use for token ownership as well as awareness of that feature by new users

**Comment by jotapea** [comment]
Locking descriptions has no effect on the Counterparty ledger, but with this change there will be a newly added variable to be considered in the validation of issuance transactions. This will certainly affect protocol, client and user experience with added complexity.

Then a "cool rebel cursed" project will come that locks the description but then continues to issue description updates. All it needs is a narrative.

Just like the reset, this just opens a pandora's box that is completely unnecessary. Isn't "immutability" one of the narratives of a project around? How come they do it without this feature?

**Comment by adamkrellenstein** [comment]
*bump*
