### ISSUE TITLE
Stalled Catchups

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2260]
https://console.cloud.google.com/logs/query;query=%22currently%20behind%20bitcoin%20core%22%0Aresource.type%3D%22gce_instance%22;cursorTimestamp=2024-09-24T21:44:50.799233540Z;duration=PT12H?project=noted-extension-407918

<img width="1446" alt="Screenshot 2024-09-24 at 5 50 41 PM" src="https://github.com/user-attachments/assets/8bf24a8e-4eab-45d3-8a71-376148b04f8c">

**Comment by adamkrellenstein** [comment]
testnet looks really stuck

**Comment by adamkrellenstein** [comment]
And again with a new testnet node: https://console.cloud.google.com/logs/query;query=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%227448402940028423273%22;cursorTimestamp=2024-09-24T23:14:44.242122237Z;startTime=2024-09-24T23:09:44.298Z;endTime=2024-09-24T23:14:44.298Z?project=noted-extension-407918

there was some restart?

**Comment by ouziel-slama** [comment]
Looks likes a RSFetcher problem:

<img width="1053" alt="Capture d’écran 2024-09-25 à 11 12 37" src="https://github.com/user-attachments/assets/6ae5a547-48c6-47e3-a586-e45b4c80344a">
<img width="885" alt="Capture d’écran 2024-09-25 à 11 13 18" src="https://github.com/user-attachments/assets/089ba2a6-32d9-46c1-b819-bf3b97868d11">

Got the same on docker-compose VM on mainnet. Fixed with a restart.

**Comment by adamkrellenstein** [comment]
Was this fixed by #2271 ?

**Comment by ouziel-slama** [comment]
yes most probably! but we must confirm before closing that the problems of the dev testnet server in recent days do not come from this bug.

**Comment by adamkrellenstein** [comment]
hopefully fixed by #2285
