### ISSUE TITLE
Missing Dispense in Mempool

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2276]
this dispense: https://explorer.unspendablelabs.com/tx/541e8d6a8f945c5ed80db436403d8d719732da53797ec97fd1c47131eedb731a
is not returned by the API:
```
> ~ http 'https://api.counterparty.io:4000/v2/transactions/541e8d6a8f945c5ed80db436403d8d719732da53797ec97fd1c47131eedb731a/dispenses?show_unconfirmed=true'
HTTP/1.1 200 OK
Alt-Svc: clear
Content-Length: 54
access-control-allow-headers: *
access-control-allow-methods: *
access-control-allow-origin: *
content-type: application/json
date: Thu, 26 Sep 2024 20:54:56 GMT
server: Werkzeug/3.0.1 Python/3.10.12
via: 1.1 google
x-bitcoin-height: 862985
x-counterparty-height: 862985
x-counterparty-ready: True

{
    "next_cursor": null,
    "result": [],
    "result_count": 0
}
```

![image](https://github.com/user-attachments/assets/60029af3-a04f-496d-8b3a-45ab655f39fe)

Was also showing up on xchain (using an old version of the node software).

**Comment by ouziel-slama** [comment]
Added a regtest test here https://github.com/CounterpartyXCP/counterparty-core/pull/2292/commits/0994d8ab48bb55ae0835c466f2616a765f649f10#diff-31b7555d89bd632f514495e7da574f6a1ccdd6f3e34214c3acc5581fe69f6761 and works well.
Probably fixed with https://github.com/CounterpartyXCP/counterparty-core/issues/2266
