### ISSUE TITLE
Configure Quantity of BTC to Send along with Asset

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2281]
This will make it faster to set up dispensers on empty addresses, if nothing else.

**Comment by DerpHerpenstein** [comment]
perhaps a more generate update to the api to have any tx generation accept an array of additional outputs to be appended prior to the change in the form of  [{address|script, value}]?    

This could allow for your specific case, but also in the future with #2197 a user could open a dispenser much like they currently do (assuming a pre-signed tx can fit in an op return)

step 1) generate a pre-signed tx to open a dispenser on the desired address for asset A and encode it in an op_return script
step 2) generate a tx to send asset A to the above address using multisig and pass {op_return_script,0} as an additional output to be added to the tx.

Then when cp decodes the tx, asset A will go to the desired address and then a dispenser will be opened

**Comment by DerpHerpenstein** [comment]
another reason it would be advantageous to have `additional_outputs:[{address|script, value}]` would be so that stamps can be made with the API without requiring external bitcoin tx construction libraries.  We currently use bitcoinjs-lib and deconstruct the results from the API into a PSBT and then add additional p2wsh outputs to encode the stamp data (olga). 

By allowing for arbitrary outputs, users will just have to do the p2wsh encoding, and then pass an array of addresses and dust values that represent the data. It lowers the barrier to entry because new devs wouldn't have to learn about the nuances of bitcoin psbt construction.

**Comment by ouziel-slama** [comment]
done herehttps://github.com/CounterpartyXCP/counterparty-core/pull/2873
you can now use the parameter `--more-outputs`:

```
"more_outputs": (
        str,
        None,
        "Additional outputs to include in the transaction in the format `<value>:<address>` or `<value>:<script>`",
    ),
```
