### ISSUE TITLE
Restart API Processes if they Crash

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2397]
to work around these kinds of issues: https://github.com/CounterpartyXCP/counterparty-core/issues/2393

**Comment by ouziel-slama** [comment]
There is only one process for the API. Except with Gunicorn :)
What I had in mind was rather to stop the main process when the API process crashes. I haven't done it for now because of Gunicorn :) because I don't know how it manages workers internally (it can for example kill some that haven't been used for a while).
For Gunicorn , I think we need to find a way to use it like it was designed for, something like:
```
gunicorn -w 4 'counterparty-server:api'
```
but it's not a small piece!

**Comment by adamkrellenstein** [comment]
What about the API Watcher?

**Comment by ouziel-slama** [comment]
yep! on process for API Watcher because he writes to the API database and then X workers for the API. Perhaps that could works with a simple [os.system](https://docs.python.org/3/library/os.html#os.system) call but not sure, I think Gunicorn should be the main process to works well.

**Comment by ouziel-slama** [comment]
also if you are able to do that we could also test `uwsgi` (for example) easily:
```
uwsgi --http 127.0.0.1:8000 --master -p 4 -w hello:app
```

**Comment by adamkrellenstein** [comment]
https://github.com/CounterpartyXCP/counterparty-core/issues/2494
