### ISSUE TITLE
Missing Sanity Checks on Fair Mints

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2421]
<img width="645" alt="Screenshot 2024-10-17 at 10 51 27 PM" src="https://github.com/user-attachments/assets/094bf69a-cf8e-4d95-b79d-387328e7c31d">
![telegram-cloud-photo-size-4-5806825711980361000-y](https://github.com/user-attachments/assets/ba2e3dd6-40c6-4949-8bef-5074a34a707f)

**Comment by jdogresorg** [comment]
![image](https://github.com/user-attachments/assets/f29969ab-446b-44a9-ac67-dbd4ca431e15)

Thanks for looking into this :)

**Comment by adamkrellenstein** [comment]
Possibly related to https://github.com/CounterpartyXCP/counterparty-core/issues/2415

**Comment by ouziel-slama** [comment]
see https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/messages/fairmint.py#L73
and here https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/messages/fairmint.py#L197
when the price of the fairminter is == 0, the mint quantity is just ignored and max_mint_per_tx is used.

**Comment by jdogresorg** [comment]
Thanks for the info. I think from a user-standpoint, it seems pretty bad to enter a quantity more than a user is allowed to mint, and auto-convert a quantity for the user to the max amount they can mint.

Glad to see that internally you adjust things so that the tx is seen as valid, but feel like the better case would be to throw an error to the user, since your changing quantities on them without their knowledge. I try to mint 5000, You convert to 1000 with no notification.

Either way, thanks for the information. 👍

**Comment by adamkrellenstein** [comment]
Let's add a sanity check to the compose function here.

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2558/commits/d1879a927cc8c2897e82c3748b2ba01ddf89b0ad

**Comment by jdogresorg** [comment]
Thank you 👍🏻
