### ISSUE TITLE
CreationError on MPMA compose

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2613]
https://counterparty.sentry.io/issues/6026051653/?alert_rule_id=15343752&alert_type=issue&notification_uuid=3909cfc7-df1b-43e1-9494-f41cf69ac0f1&project=4507062633365504&referrer=slack

**Comment by jdogresorg** [comment]
Once again, I respectfully request that when you are creating GitHub issues, you either put the full details of the issue here on github, or provide a link where anyone can review the relevant details.

I continue to see issues being created with links that linked to issues only visible two people with sentry.io accounts.

This is still supposed to be a community driven project where anyone should be able to review the issues related to code changes without any type of gatekeeping.

I am sure this is just an oversight, but I would appreciate it if you would get in the habit of posting details here rather than links to other sites to view details related to the GitHub issue. 👍🏻

**Comment by adamkrellenstein** [comment]
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/85fb87d8-0ca2-4a52-a335-54784c4b1a0d">

**Comment by jdogresorg** [comment]
Thank you, Adam, I appreciate the screenshot. At least now there is some inkling of what the issue is, though the issue is still not searchable by description on github.

Going forward, please copy and paste the issue text/ description directly, rather than just an image. 👍🏻

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2854/commits/b008cbdc50c2e05742c909166c0fc878a1f0b195
