### ISSUE TITLE
Fix dispense with source equal to the dispenser

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2716]

**Comment by jdogresorg** [comment]
A description of the problem so that people are aware of what the issue is and what the fix is would be appreciated.

I continue to see lots of issues like this being created with no real description of what the issue is or the proposed fix.

Once again, this is an open source project and is "supposed" to be transparent on all updates and issues. The lack of details on issues and fixes is frustrating, and does not encourage community participation.

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2754/commits/499a33f30054882057056c7e42262b18471be1ca
so it's impossible because this line https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/gettxinfo.py#L255
I just fixed the error message.
