### ISSUE TITLE
Stream timeout with asset issuances

### ISSUE THREAD

**Issue by DerpHerpenstein** [CounterpartyXCP/counterparty-core#2852]
The api seems to be having issues with asset issuances at the moment.

https://api.counterparty.io:4000/v2/addresses/bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4/compose/issuance?asset=A12590236770677120000&quantity=1&divisible=false&lock=true&description=STAMP%3A&exact_fee=15095&return_psbt=true

![image](https://github.com/user-attachments/assets/3b6608de-a73c-4809-b20c-c64a209d59ff)

**Comment by adamkrellenstein** [comment]
Yeah Bitcoin Core is overloaded because we're updating some nodes. We need to migrate to using electrs for initial mempool synchronization because it's not single-threaded for RPC. Cf. https://github.com/CounterpartyXCP/counterparty-core/issues/2837 and https://github.com/CounterpartyXCP/counterparty-core/issues/2843
