### ISSUE TITLE
`unpack` API call

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#352]
This should call `get_tx_info2()` (but passing the tx serialization) and then the 'unpacking' parts of `send.parse()`, `order.parse()`, etc., which should become separate functions.

The `unpack` method should return a dictionary of the message parameters (e.g. `quantity`, `asset_name`, `destination`).

**Comment by mtbitcoin** [comment]
is the "get_tx_info" API already available in master branch? I was unable to get this to work

**Comment by adamkrellenstein** [comment]
@mtbitcoin, yeah: https://github.com/CounterpartyXCP/counterpartyd/blob/master/lib/api.py#L665-L668

What was the problem?

**Comment by mtbitcoin** [comment]
This is what I am doing (escaped because I am running on windows)

curl http://x.x.x.x:4000/api/ --user user:pass -H "Content-Type: application/json; charset=UTF-8" -H "Accept: application/json, txt/javascript" --data-binary  "{\"jsonrpc\":\"2.0\",\"id\":0,\"method\":\"get_tx_info\",\"params\": {\"tx_hex\":\"0100000001ad369b446173cea81b150b856cea7bb2bab37595703ee3b2fe0c9e33bd416038000000008a4730440220591be7c1ef5b300eb1f72c755a28d54c34a11826e9a5d77dd310a987fd721cb30220765ce88463e00662d803e22b6457b14db0df5640376187a7efd30c9607d886d70141040286a47e8b11624c510881521b73a02929b9615d219100300c651771c0cf46c04b14cfa790e3f66940d11b5ab3d8ae81a3577473fbd36e2fc2b3d69e91d9af62ffffffff03781e0000000000001976a914b80c64c20a65646ae8238eeb019cc2380ca0617f88ac781e00000000000089512103e70605eeb731a017ad895d071893f3a9f2a69f1ff79106b2c7784608517d9870210381221a27700043f77357cd1becdd1c6f869c052b4960326ca23627fd713109ba41040286a47e8b11624c510881521b73a02929b9615d219100300c651771c0cf46c04b14cfa790e3f66940d11b5ab3d8ae81a3577473fbd36e2fc2b3d69e91d9af6253ae505f0000000000001976a914fa0692315a9f730b403e4be216b9b5d05492e81888ac00000000\"}}"

And the response that I am getting is

--> {"id": 0, "error": {"message": "Invalid params", "code": -32602}, "jsonrpc": "2.0"}

The "unpack" method however works as expected using the sample above

**Comment by adamkrellenstein** [comment]
@mtbitcoin, fixed: bafc122

**Comment by mtbitcoin** [comment]
Works. Thanks

**Comment by mtbitcoin** [comment]
Does the "unpack" work for anything other than sends? I tried to unpack an order and an asset issuance but received the following  

(for getrawtransaction 140a2b99d960b828fe395cbc5d781bba31b117d3c3100db36a27db3147c7f6e8)

C:\>curl http://localhost:4000/api/ --user x:X -H "Content-Type
: application/json; charset=UTF-8" -H "Accept: application/json, txt/javascript" --data-bi
nary  "{\"jsonrpc\":\"2.0\",\"id\":0,\"method\":\"unpack\",\"params\": {\"data_hex\":\"000
000140000002bec05ea4e000000000000000000000000000000000000214d696461732052657a6572766520446
56d6f20436f696e7320284d52434f494e29\"}}"
{"id": 0, "error": {"message": "Server error", "data": {"args": ["'module' object has no a
ttribute 'unpack'"], "message": "'module' object has no attribute 'unpack'", "type": "Attr
ibuteError"}, "code": -32000}, "jsonrpc": "2.0"}

**Comment by adamkrellenstein** [comment]
@mtbitcoin, not at the moment. Right now, it works for all messages whose modules have implemented `unpack()`.

**Comment by mtbitcoin** [comment]
Is there an API to decode the data_hex for non-send transactions ?

**Comment by adamkrellenstein** [comment]
@mtbitcoin, it's all done with that method, it's just the other messages haven't had it implemented yet. Is it a priority for you?

**Comment by mtbitcoin** [comment]
ok. so eventually we will be able to decode the data_hex with the unpack method? Its not an ultimate priority now but I've seen this requested a couple of times and can be useful for reading raw  transactions. I was planning to use this for a CP transaction builder and decoder on blockscan.

**Comment by adamkrellenstein** [comment]
Definitely
